# Docker Base Image
FROM node:20-alpine

# Set Working Directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Run application
CMD ["npm", "start"]