# Docker Base Image
FROM node:20-alpine

# Set Working Directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 5001

# Run application
CMD ["npm", "start"]